//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCTool.PLC {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServoIO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServoIO() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLCTool.PLC.ServoIO", typeof(ServoIO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 编码器A相 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_0 {
            get {
                return ResourceManager.GetString("PLC1I0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器B相 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_1 {
            get {
                return ResourceManager.GetString("PLC1I0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷伺服正极限 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_2 {
            get {
                return ResourceManager.GetString("PLC1I0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷伺服负极限 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_3 {
            get {
                return ResourceManager.GetString("PLC1I0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷伺服原点 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_4 {
            get {
                return ResourceManager.GetString("PLC1I0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷传感器1-1 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_5 {
            get {
                return ResourceManager.GetString("PLC1I0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷传感器1-2 的本地化字符串。
        /// </summary>
        internal static string PLC1I0_6 {
            get {
                return ResourceManager.GetString("PLC1I0_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I0_7 {
            get {
                return ResourceManager.GetString("PLC1I0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I1_0 {
            get {
                return ResourceManager.GetString("PLC1I1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I1_1 {
            get {
                return ResourceManager.GetString("PLC1I1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I1_2 {
            get {
                return ResourceManager.GetString("PLC1I1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急停止 的本地化字符串。
        /// </summary>
        internal static string PLC1I1_3 {
            get {
                return ResourceManager.GetString("PLC1I1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string PLC1I1_4 {
            get {
                return ResourceManager.GetString("PLC1I1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string PLC1I1_5 {
            get {
                return ResourceManager.GetString("PLC1I1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归零 的本地化字符串。
        /// </summary>
        internal static string PLC1I1_6 {
            get {
                return ResourceManager.GetString("PLC1I1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷处无布检测 的本地化字符串。
        /// </summary>
        internal static string PLC1I1_7 {
            get {
                return ResourceManager.GetString("PLC1I1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷处下限检测 的本地化字符串。
        /// </summary>
        internal static string PLC1I2_0 {
            get {
                return ResourceManager.GetString("PLC1I2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进布上料无布检测 的本地化字符串。
        /// </summary>
        internal static string PLC1I2_1 {
            get {
                return ResourceManager.GetString("PLC1I2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进布下限检测 的本地化字符串。
        /// </summary>
        internal static string PLC1I2_2 {
            get {
                return ResourceManager.GetString("PLC1I2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I2_3 {
            get {
                return ResourceManager.GetString("PLC1I2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I2_4 {
            get {
                return ResourceManager.GetString("PLC1I2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I2_5 {
            get {
                return ResourceManager.GetString("PLC1I2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位 的本地化字符串。
        /// </summary>
        internal static string PLC1I2_6 {
            get {
                return ResourceManager.GetString("PLC1I2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I2_7 {
            get {
                return ResourceManager.GetString("PLC1I2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主动辊伺服报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_0 {
            get {
                return ResourceManager.GetString("PLC1I3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验布站伺服报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_1 {
            get {
                return ResourceManager.GetString("PLC1I3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进布站进布辊变频器报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_2 {
            get {
                return ResourceManager.GetString("PLC1I3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进布站分丝辊变频器报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_3 {
            get {
                return ResourceManager.GetString("PLC1I3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷站收卷辊变频器报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_4 {
            get {
                return ResourceManager.GetString("PLC1I3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷站分丝辊变频器报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_5 {
            get {
                return ResourceManager.GetString("PLC1I3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开卷站主动辊变频器报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_6 {
            get {
                return ResourceManager.GetString("PLC1I3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摆布变频器报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I3_7 {
            get {
                return ResourceManager.GetString("PLC1I3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_0 {
            get {
                return ResourceManager.GetString("PLC1I4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_1 {
            get {
                return ResourceManager.GetString("PLC1I4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_2 {
            get {
                return ResourceManager.GetString("PLC1I4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_3 {
            get {
                return ResourceManager.GetString("PLC1I4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_4 {
            get {
                return ResourceManager.GetString("PLC1I4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_5 {
            get {
                return ResourceManager.GetString("PLC1I4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_6 {
            get {
                return ResourceManager.GetString("PLC1I4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I4_7 {
            get {
                return ResourceManager.GetString("PLC1I4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷纠偏报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I5_0 {
            get {
                return ResourceManager.GetString("PLC1I5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷纠偏报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I5_1 {
            get {
                return ResourceManager.GetString("PLC1I5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主轴伺服报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I5_2 {
            get {
                return ResourceManager.GetString("PLC1I5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张力伺服报警 的本地化字符串。
        /// </summary>
        internal static string PLC1I5_3 {
            get {
                return ResourceManager.GetString("PLC1I5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I5_4 {
            get {
                return ResourceManager.GetString("PLC1I5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I5_5 {
            get {
                return ResourceManager.GetString("PLC1I5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I5_6 {
            get {
                return ResourceManager.GetString("PLC1I5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1I5_7 {
            get {
                return ResourceManager.GetString("PLC1I5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷脉冲 的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_0 {
            get {
                return ResourceManager.GetString("PLC1Q0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张力伺服脉冲 的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_1 {
            get {
                return ResourceManager.GetString("PLC1Q0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷方向 的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_2 {
            get {
                return ResourceManager.GetString("PLC1Q0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主辊伺服脉冲 的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_3 {
            get {
                return ResourceManager.GetString("PLC1Q0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_4 {
            get {
                return ResourceManager.GetString("PLC1Q0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_5 {
            get {
                return ResourceManager.GetString("PLC1Q0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_6 {
            get {
                return ResourceManager.GetString("PLC1Q0_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张力伺服方向 的本地化字符串。
        /// </summary>
        internal static string PLC1Q0_7 {
            get {
                return ResourceManager.GetString("PLC1Q0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主辊伺服方向 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_0 {
            get {
                return ResourceManager.GetString("PLC1Q1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三色灯-绿 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_1 {
            get {
                return ResourceManager.GetString("PLC1Q1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三色灯-黄 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_2 {
            get {
                return ResourceManager.GetString("PLC1Q1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三色灯-红 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_3 {
            get {
                return ResourceManager.GetString("PLC1Q1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三色灯-蜂鸣器 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_4 {
            get {
                return ResourceManager.GetString("PLC1Q1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分边直流电机1 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_5 {
            get {
                return ResourceManager.GetString("PLC1Q1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分边直流电机2 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_6 {
            get {
                return ResourceManager.GetString("PLC1Q1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摆布对中启停 的本地化字符串。
        /// </summary>
        internal static string PLC1Q1_7 {
            get {
                return ResourceManager.GetString("PLC1Q1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_0 {
            get {
                return ResourceManager.GetString("PLC1Q2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机电源 的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_1 {
            get {
                return ResourceManager.GetString("PLC1Q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_2 {
            get {
                return ResourceManager.GetString("PLC1Q2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位输出 的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_3 {
            get {
                return ResourceManager.GetString("PLC1Q2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠偏器自动 的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_4 {
            get {
                return ResourceManager.GetString("PLC1Q2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠偏器回中 的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_5 {
            get {
                return ResourceManager.GetString("PLC1Q2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_6 {
            get {
                return ResourceManager.GetString("PLC1Q2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q2_7 {
            get {
                return ResourceManager.GetString("PLC1Q2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_0 {
            get {
                return ResourceManager.GetString("PLC1Q3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_1 {
            get {
                return ResourceManager.GetString("PLC1Q3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_2 {
            get {
                return ResourceManager.GetString("PLC1Q3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_3 {
            get {
                return ResourceManager.GetString("PLC1Q3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_4 {
            get {
                return ResourceManager.GetString("PLC1Q3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_5 {
            get {
                return ResourceManager.GetString("PLC1Q3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_6 {
            get {
                return ResourceManager.GetString("PLC1Q3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC1Q3_7 {
            get {
                return ResourceManager.GetString("PLC1Q3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴正限位 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_0 {
            get {
                return ResourceManager.GetString("PLC2I0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴负限位 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_1 {
            get {
                return ResourceManager.GetString("PLC2I0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴原点 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_2 {
            get {
                return ResourceManager.GetString("PLC2I0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷伺服正极限 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_3 {
            get {
                return ResourceManager.GetString("PLC2I0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷伺服负极限 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_4 {
            get {
                return ResourceManager.GetString("PLC2I0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷伺服原点 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_5 {
            get {
                return ResourceManager.GetString("PLC2I0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴正限位 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_6 {
            get {
                return ResourceManager.GetString("PLC2I0_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴负限位 的本地化字符串。
        /// </summary>
        internal static string PLC2I0_7 {
            get {
                return ResourceManager.GetString("PLC2I0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴原点 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_0 {
            get {
                return ResourceManager.GetString("PLC2I1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷传感器1-2 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_1 {
            get {
                return ResourceManager.GetString("PLC2I1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放卷传感器1-1 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_2 {
            get {
                return ResourceManager.GetString("PLC2I1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对中启停 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_3 {
            get {
                return ResourceManager.GetString("PLC2I1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伺服归零 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_4 {
            get {
                return ResourceManager.GetString("PLC2I1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卷标到位检测 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_5 {
            get {
                return ResourceManager.GetString("PLC2I1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出气缸前限位 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_6 {
            get {
                return ResourceManager.GetString("PLC2I1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出气缸后限位 的本地化字符串。
        /// </summary>
        internal static string PLC2I1_7 {
            get {
                return ResourceManager.GetString("PLC2I1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真空检测 的本地化字符串。
        /// </summary>
        internal static string PLC2I2_0 {
            get {
                return ResourceManager.GetString("PLC2I2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_1 {
            get {
                return ResourceManager.GetString("PLC2I2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_2 {
            get {
                return ResourceManager.GetString("PLC2I2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_3 {
            get {
                return ResourceManager.GetString("PLC2I2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_4 {
            get {
                return ResourceManager.GetString("PLC2I2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_5 {
            get {
                return ResourceManager.GetString("PLC2I2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_6 {
            get {
                return ResourceManager.GetString("PLC2I2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2I2_7 {
            get {
                return ResourceManager.GetString("PLC2I2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴脉冲 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_0 {
            get {
                return ResourceManager.GetString("PLC2Q0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷脉冲 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_1 {
            get {
                return ResourceManager.GetString("PLC2Q0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴方向 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_2 {
            get {
                return ResourceManager.GetString("PLC2Q0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴脉冲 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_3 {
            get {
                return ResourceManager.GetString("PLC2Q0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴使能 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_4 {
            get {
                return ResourceManager.GetString("PLC2Q0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_5 {
            get {
                return ResourceManager.GetString("PLC2Q0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴使能 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_6 {
            get {
                return ResourceManager.GetString("PLC2Q0_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卷方向 的本地化字符串。
        /// </summary>
        internal static string PLC2Q0_7 {
            get {
                return ResourceManager.GetString("PLC2Q0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴方向 的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_0 {
            get {
                return ResourceManager.GetString("PLC2Q1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真空电磁阀 的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_1 {
            get {
                return ResourceManager.GetString("PLC2Q1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸电磁阀 的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_2 {
            get {
                return ResourceManager.GetString("PLC2Q1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A轴使能 的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_3 {
            get {
                return ResourceManager.GetString("PLC2Q1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_4 {
            get {
                return ResourceManager.GetString("PLC2Q1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_5 {
            get {
                return ResourceManager.GetString("PLC2Q1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_6 {
            get {
                return ResourceManager.GetString("PLC2Q1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PLC2Q1_7 {
            get {
                return ResourceManager.GetString("PLC2Q1_7", resourceCulture);
            }
        }
    }
}
